/*******************************************************************************
	Generated by: DLL to C version 3.18
	Date: 2019-3-2
	Description: The declaration of functions and variables for air.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#if !defined(D2SL_AIR_SUPP_H_00005AFD_INCLUDED_)
#define D2SL_AIR_SUPP_H_00005AFD_INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#ifdef __cplusplus
extern "C" {
#endif


#include <windows.h>

/* .textbss section, RVA range: 0x1000 - 0x11000 */
__declspec(align(16)) extern UCHAR Air_textbss[0x10000];

/* .text section, RVA range: 0x11000 - 0x19000 */
__declspec(align(16)) extern UCHAR Air_text[0x8000];

/* .rdata section, RVA range: 0x19000 - 0x1C000 */
__declspec(align(16)) extern UCHAR Air_rdata[0x3000];

/* .data section, RVA range: 0x1C000 - 0x1D000 */
__declspec(align(16)) extern UCHAR Air_data[0x1000];

/* .idata section, RVA range: 0x1D000 - 0x1E000 */
__declspec(align(16)) extern UCHAR Air_idata[0x1000];

/* .msvcjmc section, RVA range: 0x1E000 - 0x1F000 */
__declspec(align(16)) extern UCHAR Air_msvcjmc[0x1000];

/* .00cfg section, RVA range: 0x1F000 - 0x20000 */
__declspec(align(16)) extern UCHAR Air_00cfg[0x1000];

/* Data for initialization. */
extern UCHAR Air_InitData[0xB5D];


#ifdef __cplusplus
}
#endif


extern HMODULE g_hAir;

/* Description: Initialize the DLL. */
BOOL Air_Init();

/* Description: Load the DLL. */
BOOL Air_LoadLibrary();

/* Description: Free the DLL. */
BOOL Air_FreeLibrary();

/*
	Description: Access any address in the DLL.
	Parameters:
		rvaAddr: The RVA address you want to access.
*/
void* __stdcall Air_RVA(DWORD rvaAddr);

/*
	Description: Retrieves the address of an exported function or variable in the DLL.
	Parameters:
		lpProcName: The function or variable name.
*/
FARPROC Air_GetProcAddress(LPCSTR lpProcName);

#endif // !defined(D2SL_AIR_SUPP_H_00005AFD_INCLUDED_)